# Setup
title:               Rahul Yumlembam
tagline:             'Machine Story'
description:         'A no-nonsense blog theme—like a well-tuned ML model, minimal overfitting, maximum readability.'
url:                 'http://127.0.0.1:4000/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rahul Yumlembam
  url:               'http://127.0.0.1:4000/'
  email:             rahul@example.com  # Update with your real email if needed

# Plugins
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-9E77406NL6
